# domain: oanhthai-cms.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
# url: https://oanhthai-cms.github.io  # the base hostname and protocol for your site, e.g. http://example.com
# baseurl: /oanhthai-cms.github.io/  

# lsi: false
# safe: true
# source: [your repo's top level directory]
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge

theme: minima

collections:
  authors:
    output: true
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag